<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, call)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT call (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl, at)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT alsa_device EMPTY>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT pcm_config EMPTY>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call) #REQUIRED>
  <!ELEMENT device EMPTY>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT path EMPTY>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ELEMENT at EMPTY>
  <!ATTLIST at node CDATA #REQUIRED>
  <!ATTLIST at cmd CDATA #REQUIRED>
  <!ELEMENT at EMPTY>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="0"
               card_name="OdinAudioCard"
               device_id="0">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>

    <playback>
      <path name="on">
        <ctl name="DAC1 L Mux" val="IF1 DAC" />
        <ctl name="DAC1 R Mux" val="IF1 DAC" />
        <ctl name="DAC1 MIXL DAC1 Switch" val="1" />
        <ctl name="DAC1 MIXR DAC1 Switch" val="1" />
        <ctl name="Stereo DAC MIXL DAC L1 Switch" val="1" />
        <ctl name="Stereo DAC MIXR DAC R1 Switch" val="1" />
      </path>
      <path name="off">
        <ctl name="DAC1 MIXL DAC1 Switch" val="0" />
        <ctl name="DAC1 MIXR DAC1 Switch" val="0" />
        <ctl name="Stereo DAC MIXL DAC L1 Switch" val="0" />
        <ctl name="Stereo DAC MIXR DAC R1 Switch" val="0" />
      </path>
          
      <device name="headphone">
        <path name="on">
          <ctl name="HPOVOL MIXL DAC1 Switch" val="1" />
          <ctl name="HPOVOL MIXR DAC1 Switch" val="1" />
          <ctl name="HPO MIX HPVOL Switch" val="1" />
        </path>
        <path name="off">     
          <ctl name="HPO MIX HPVOL Switch" val="0" />
          <ctl name="HPOVOL MIXL DAC1 Switch" val="0" />
          <ctl name="HPOVOL MIXR DAC1 Switch" val="0" />
        </path>
      </device>
      <device name="speaker">
        <path name="on">      
          <ctl name="OUT MIXL DAC L1 Switch" val="1" />
          <ctl name="OUT MIXR DAC R1 Switch" val="1" />
          <ctl name="LOUT MIX OUTMIX L Switch" val="1" />
          <ctl name="LOUT MIX OUTMIX R Switch" val="1" />
        </path>
        <path name="off">
          <ctl name="LOUT MIX OUTMIX L Switch" val="0" />
          <ctl name="LOUT MIX OUTMIX R Switch" val="0" />
          <ctl name="OUT MIXL DAC L1 Switch" val="0" />
          <ctl name="OUT MIXR DAC R1 Switch" val="0" />
        </path>
      </device>
    </playback>
 </alsa_device>

<alsa_device name="music"
               card_id="0"
               card_name="OdinAudioCard"
               device_id="1">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>

    <capture>
      <path name="on">
        <ctl name="IF1 ADC1 IN1 Mux" val="IF_ADC1" />
        <ctl name="IF1 ADC1 IN2 Mux" val="IF1_ADC1_IN1" />
      </path>    
      <path name="off">
      </path>          
      
      <device name="builtin-mic">
        <path name="on">
           <ctl name="Stereo1 DMIC Mux" val="DMIC1" />
           <ctl name="Stereo1 ADC2 Mux" val="DMIC" />
           <ctl name="Sto1 ADC MIXL ADC2 Switch" val="1" />
           <ctl name="Sto1 ADC MIXR ADC2 Switch" val="1" />
        </path>
        <path name="off">
           <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0" />
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
           <ctl name="Stereo1 ADC Mux" val="ADC1L ADC2R" />
           <ctl name="Stereo1 ADC1 Mux" val="ADC" />
           <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1" />
           <ctl name="RECMIXL BST1 Switch" val="1" />
           <ctl name="RECMIXR BST1 Switch" val="1" />
        </path>
        <path name="off">
           <ctl name="Sto1 ADC MIXL ADC1 Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="0" />
           <ctl name="RECMIXL BST1 Switch" val="0" />
           <ctl name="RECMIXR BST1 Switch" val="0" />
        </path>
      </device>
      <device name="bt-sco-mic">
        <path name="on">
           <ctl name="DAC MIXL Sto DAC Mix L Switch" val="0" />
           <ctl name="DAC MIXR DAC R2 Switch" val="0" />
           <ctl name="Sto2 ADC MIXR ADC1 Switch" val="0" />
           <ctl name="DAC MIXR DAC L2 Switch" val="1" />
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="1" />
           <ctl name="Stereo1 ADC1 Mux" val="DAC MIX" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1" />
           <ctl name="Stereo DAC MIXR DAC R1 Switch" val="1" />
        </path>
        <path name="off">
           <ctl name="DAC MIXR DAC L2 Switch" val="0" />
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="0" />
           <ctl name="Stereo DAC MIXR DAC R1 Switch" val="0" />
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name ="voice-call"
           card_id="0"
           card_name="OdinAudioCard"
           device_id="2">
    <pcm_config rate="16000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    
    <call>
      <path name="on">
        <!--playback paths-->
        <ctl name="DAC L2 Mux" val="IF2 DAC" />
        <ctl name="DAC R2 Mux" val="IF2 DAC" />
        <ctl name="Stereo DAC MIXL DAC L2 Switch" val="1" />
        <ctl name="Stereo DAC MIXR DAC R2 Switch" val="1" />
        <ctl name="Voice Call" val="1"/>
      </path>
      <path name="off">
        <ctl name="Stereo DAC MIXL DAC L2 Switch" val="0" />
        <ctl name="Stereo DAC MIXR DAC R2 Switch" val="0" />
        <ctl name="Voice Call" val="0"/>
      </path>
      
      <device name="headphone">
        <path name="on">
          <ctl name="HPOVOL MIXL DAC1 Switch" val="1" />
          <ctl name="HPOVOL MIXR DAC1 Switch" val="1" />
          <ctl name="HPO MIX HPVOL Switch" val="1" />
        </path>
        <path name="off">
          <ctl name="HPOVOL MIXL DAC1 Switch" val="0" />
          <ctl name="HPOVOL MIXR DAC1 Switch" val="0" />
          <ctl name="HPO MIX HPVOL Switch" val="0" />
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="OUT MIXL DAC L1 Switch" val="1" />
          <ctl name="OUT MIXR DAC R1 Switch" val="1" />
          <ctl name="LOUT MIX OUTMIX L Switch" val="1" />
          <ctl name="LOUT MIX OUTMIX R Switch" val="1" />  
        </path>
        <path name="off">
          <ctl name="OUT MIXL DAC L1 Switch" val="0" />
          <ctl name="OUT MIXR DAC R1 Switch" val="0" />
          <ctl name="LOUT MIX OUTMIX L Switch" val="0" />
          <ctl name="LOUT MIX OUTMIX R Switch" val="0" /> 
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
           <ctl name="Mono DAC MIXL DAC L2 Switch" val="1" />
           <ctl name="Mono DAC MIXR DAC R2 Switch" val="1" />
           <ctl name="MONOVOL MIX DAC R2 Switch" val="1" />
           <ctl name="MONOVOL MIX DAC L2 Switch" val="1" />
           <ctl name="MONOAmp MIX MONOVOL Switch" val="1" />
        </path>
        <path name="off">
	   <ctl name="Mono DAC MIXL DAC L2 Switch" val="0" />
           <ctl name="Mono DAC MIXR DAC R2 Switch" val="0" />
           <ctl name="MONOVOL MIX DAC R2 Switch" val="0" />
           <ctl name="MONOVOL MIX DAC L2 Switch" val="0" />
           <ctl name="MONOAmp MIX MONOVOL Switch" val="0" />
        </path>
      </device>
    </call>
    <call>
      <path name="on">
        <!--capture paths-->
        <ctl name="IF2 ADC Mux" val="IF_ADC2" />  
        <ctl name="Voice Call" val="1"/>
      </path>
      <path name="off">
        <ctl name="Voice Call" val="0"/>
      </path>
          
      <device name="builtin-mic">
        <path name="on">
           <ctl name="Mono DMIC L Mux" val="DMIC1" />
           <ctl name="Mono DMIC R Mux" val="DMIC1" />
           <ctl name="Mono ADC L2 Mux" val="DMIC" />
           <ctl name="Mono ADC R2 Mux" val="DMIC" />
           <ctl name="Mono ADC MIXL ADC2 Switch" val="1" />
           <ctl name="Mono ADC MIXR ADC2 Switch" val="1" />
           <!-- call recording to AIF1 path -->     
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="1" />
           <ctl name="DAC MIXL Sto DAC Mix L Switch" val="1" />
           <ctl name="Stereo1 ADC1 Mux" val="DAC MIX" />
           <ctl name="Sto1 ADC MIXL ADC1 Switch" val="1" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1" />
        </path>
        <path name="off">
           <ctl name="Mono ADC MIXL ADC2 Switch" val="0" />
           <ctl name="Mono ADC MIXR ADC2 Switch" val="0" />
           <!-- call recording to AIF1 path -->     
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="0" />
           <ctl name="DAC MIXL Sto DAC Mix L Switch" val="0" />
           <ctl name="Sto1 ADC MIXL ADC1 Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="0" />
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
           <ctl name="Mono ADC L Mux" val="ADC1" />
           <ctl name="Mono ADC R Mux" val="ADC2" />
           <ctl name="Mono ADC L1 Mux" val="ADC1 ADC3" />
           <ctl name="Mono ADC R1 Mux" val="ADC2 ADC3" />
           <ctl name="Mono ADC MIXL ADC1 Switch" val="1" />
           <ctl name="Mono ADC MIXR ADC1 Switch" val="1" />
           <ctl name="RECMIXL BST1 Switch" val="1" />
           <ctl name="RECMIXR BST1 Switch" val="1" />
           <!-- call recording to AIF1 path -->     
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="1" />
           <ctl name="DAC MIXL Sto DAC Mix L Switch" val="1" />
           <ctl name="Stereo1 ADC2 Mux" val="DAC MIX" />
           <ctl name="Sto1 ADC MIXL ADC2 Switch" val="1" />
           <ctl name="Sto1 ADC MIXR ADC2 Switch" val="1" />
        </path>
        <path name="off">
           <ctl name="Mono ADC MIXL ADC1 Switch" val="0" />
           <ctl name="Mono ADC MIXR ADC1 Switch" val="0" />
           <ctl name="RECMIXL BST1 Switch" val="0" />
           <ctl name="RECMIXR BST1 Switch" val="0" />
           <!-- call recording to AIF1 path --> 
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="0" />
           <ctl name="DAC MIXL Sto DAC Mix L Switch" val="0" />
           <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0" />
       </path>
      </device>
    </call>
  </alsa_device>  

  <alsa_device name ="bt-voice-call"
           card_id="0"
           card_name="OdinAudioCard"
           device_id="3">
    <pcm_config rate="8000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
      </path>
      <path name="off">
      </path>
      <device name="bt-sco">
        <path name="on">
           <ctl name="DAC L2 Mux" val="IF2 DAC" />
           <ctl name="DAC R2 Mux" val="IF2 DAC" />
           <ctl name="DAC MIXL DAC L2 Switch" val="1" />
           <ctl name="DAC MIXR DAC R2 Switch" val="1" />
           <ctl name="Stereo2 ADC1 Mux" val="DAC MIX" />
           <ctl name="Sto2 ADC MIXL ADC1 Switch" val="1" />
           <ctl name="Sto2 ADC MIXR ADC1 Switch" val="1" />
           <ctl name="BT Call" val="1" />
           <!-- Please remove it while implemented start -->
           <!-- bt call recording to AIF1 path -->
           <ctl name="DAC MIXL Sto DAC Mix L Switch" val="0" />
           <ctl name="DAC MIXR DAC R2 Switch" val="0" />
           <ctl name="Sto2 ADC MIXR ADC1 Switch" val="0" />
           <ctl name="DAC MIXR DAC L2 Switch" val="1" />
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="1" />
           <ctl name="Stereo1 ADC1 Mux" val="DAC MIX" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="1" />
           <ctl name="Stereo DAC MIXR DAC R1 Switch" val="1" />
           <!-- mute the normal capture path -->
           <ctl name="RECMIXL BST1 Switch" val="0" />
           <ctl name="RECMIXR BST1 Switch" val="0" />
           <ctl name="Sto1 ADC MIXL ADC2 Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC2 Switch" val="0" />
           <!-- Please remove it while implemented end -->
        </path>
        <path name="off">
           <ctl name="DAC MIXL DAC L2 Switch" val="0" />
           <ctl name="DAC MIXR DAC R2 Switch" val="0" />
           <ctl name="Sto2 ADC MIXL ADC1 Switch" val="0" />
           <ctl name="Sto2 ADC MIXR ADC1 Switch" val="0" />
           <ctl name="BT Call" val="0" />
           <ctl name="DAC MIXR DAC L2 Switch" val="0" />
           <ctl name="DAC MIXR Sto DAC Mix R Switch" val="0" />
           <ctl name="Sto1 ADC MIXR ADC1 Switch" val="0" />
           <ctl name="Stereo DAC MIXR DAC R1 Switch" val="0" />
        </path>
      </device>
    </call>
    <call>
      <device name="bt-sco-mic">
        <path name="on">
           <ctl name="DAC1 L Mux" val="IF3 DAC" />
           <ctl name="DAC1 R Mux" val="IF3 DAC" />
           <ctl name="DAC1 MIXL DAC1 Switch" val="1" />
           <ctl name="DAC1 MIXR DAC1 Switch" val="1" />
           <ctl name="Mono DAC MIXL DAC L1 Switch" val="1" />
           <ctl name="Mono DAC MIXR DAC R1 Switch" val="1" />
           <ctl name="Mono ADC L1 Mux" val="Mono DAC MIXL" />
           <ctl name="Mono ADC R1 Mux" val="Mono DAC MIXR" />
           <ctl name="Mono ADC MIXL ADC1 Switch" val="1" />
           <ctl name="Mono ADC MIXR ADC1 Switch" val="1" />
        </path>
        <path name="off">
           <ctl name="DAC1 MIXL DAC1 Switch" val="0" />
           <ctl name="DAC1 MIXR DAC1 Switch" val="0" />
           <ctl name="Mono DAC MIXL DAC L1 Switch" val="0" />
           <ctl name="Mono DAC MIXR DAC R1 Switch" val="0" />
           <ctl name="Mono ADC MIXL ADC1 Switch" val="0" />
           <ctl name="Mono ADC MIXR ADC1 Switch" val="0" />
        </path>
      </device>
    </call>
  </alsa_device>  
  
</AudioConfigs>
